title: exp^lead
author: Sumedh
email: guptesumedh+neoteric@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A series of blogs and experiments 
theme: minima
# social links
twitter_username: guptesumedh # DO NOT include the @ character, or else the build will fail!
github_username:  sumedhgupte # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

