title : "exp^LEAD"
author: Sumedh
email: guptesumedh+explead@gmail.com
description:  EXPeriments for **LE**arning and ADaptation
theme: minima
# social links
twitter_username: guptesumedh # DO NOT include the @ character, or else the build will fail!
github_username:  sumedhgupte # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
